### ISSUE TITLE
[Suggestion] Scoreboard

### ISSUE THREAD

**Issue by weberlepecheur** [Weefle/SkWaze#1]
Hello,

I propose to add scoreboard for the server, a group of players with a variable list or a specific player.
SkRayFall scoreboard for 1 player not working on my server and those of Skellett are a bit difficult to understand.

> Create/make/Delete scoreboard
> Set/add/remove/substract score for an entry on scoreboard
> Wipe scoreboard after %time% seconds

Exemple :
`[waze] (create | make) [a] scoreboard to (%players% | %{players::*}% | %all players%)`
etc...

**Comment by Weefle** [comment]
Vu que tu as l'air français, je vais te répondre en français 😄 
En effet ce serait intéressant comme ajout, je vais travailler dessus dès que je le pourrais! 😃

**Comment by Weefle** [comment]
Cette suggestion a été ajoutée.
