### ISSUE TITLE
Question, ignore air and water when build

### ISSUE THREAD

**Issue by Ghiranos** [Weefle/SkWaze#5]
```
on right click on entity:
	set {.id} to citizen id of event-entity
	let citizen with id {.id} build schematic "harbor" at player with speed 1 to player```
```
Is it possible to make the builder to **ignore air** and water ?

**Comment by Weefle** [comment]
Hi, I can't implement it of course, I'll make an update soon.

**Comment by Ghiranos** [comment]
> Hi, I could implement it of course, I'll make an update soon.

ok ill wait for the update

oh and also how can i detect when building is done?

**Comment by Weefle** [comment]
There is no way to check this for now

**Comment by Weefle** [comment]
Feature added
